services:
  - type: web
    name: restaurant-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db  # Имя вашей базы данных на Render
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
